### ISSUE TITLE
Cannot load data from subdirectories

### ISSUE THREAD

**Issue by ghost** [yosymfony/spress-plugin-dataloader#3]
Due to the use of `scandir()` to list files, it's not possible to have data organized in subdirectories.

Would you consider the possibility to use subdirectories? If so, I may provide a PR.

How I see it (for a possible PR):
- build the filename by replacing `.` by `/
- build a pattern: `"{$this->dataDir}/{$item}.*"`
- use the pattern with `glob()`

**Comment by yosymfony** [comment]
Hi.
It seems good. Could you make the PR?

**Comment by ghost** [comment]
Actually, I noticed it would introduce a BC break: if a file name already contains a dot, which could be a way to namespace-like the files when listed (for example: `home.data1.yaml,` `home.data2.yaml`)

I'm not so sure anymore it's a good idea...

**Comment by yosymfony** [comment]
Right, that's true
